feat: add get-pip.py version handling

diff --git a/scripts/build.d/python b/scripts/build.d/python
--- a/scripts/build.d/python
+++ b/scripts/build.d/python
@@ -104,11 +104,16 @@ pushd ${DEVENVFLAVORROOT}/${DEVENVFLAVOR}/src/${pkgfull} > /dev/null
   PY_BIN=${PREFIX}/bin/python3
   CURL_URL=https://bootstrap.pypa.io/get-pip.py
 
-  IFS='.' read -ra VER <<< ${VERSION}
+  IFS='.' read -ra VER <<< "${VERSION}"
 
-  if [[ ${VER[0]} == "v2" ]]; then
+  if [[ "${VER[0]}" == "v2" || "${VER[0]}" == "2" ]]; then
     PY_BIN=${PREFIX}/bin/python
     CURL_URL=https://bootstrap.pypa.io/pip/2.7/get-pip.py
+  elif (( "${VER[0]}" == 3 && "${VER[1]}" < 6 )); then
+    echo "ERROR: Python ${pkgver} is below 3.6. get-pip is not supported."
+    exit 1
+  elif (( "${VER[0]}" == 3 && "${VER[1]}" < 9 )); then
+    CURL_URL="https://bootstrap.pypa.io/pip/${VER[0]}.${VER[1]}/get-pip.py"
   fi
 
   curl ${CURL_URL} | ${PY_BIN}
